[versions]
ktx_version = "1.10.1"
junit_version = "4.13.2"
room_version = "2.5.2"
lifecycle_version = "2.6.1"
accompanist_version = "0.30.1"
compose_navigation = "2.6.0"
compose_activity = "1.7.2"
truth_version = "1.1.3"
ext_junit_version = "1.1.5"
espresso_version = "3.5.1"
compose_bom = "2023.06.01"
turbine_version = "0.12.3"
splashscreen_version = "1.0.1"
concurrent-version = "1.1.0"
camera-version = "1.3.0-beta01"
coil-version = "2.4.0"
media3_version = "1.1.0"


# Plugin version
android_version = "8.0.2"
kotlin_version = "1.8.10"
spotless_version = "6.14.1"
ksp_version = "1.8.10-1.0.9"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx_version" }
junit = { group = "junit", name = "junit", version.ref = "junit_version" }
room_compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room_version" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room_version" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room_version" }
lifecycle-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle_version" }
lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle_version" }
accompanist-painter = { group = "com.google.accompanist", name = "accompanist-drawablepainter", version.ref = "accompanist_version" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist_version" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "compose_activity" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose_navigation" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth_version" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "ext_junit_version" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso_version" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine_version" }
splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen_version" }
concurrent-kts = { group = "androidx.concurrent", name = "concurrent-futures-ktx", version.ref = "concurrent-version" }
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "camera-version" }
camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camera-version" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camera-version" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camera-version" }
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil-version" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-version" }
media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "media3_version" }
media3-effect = { group = "androidx.media3", name = "media3-effect", version.ref = "media3_version" }
media3-transformer = { group = "androidx.media3", name = "media3-transformer", version.ref = "media3_version" }
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3_version" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3_version" }


compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose_bom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-test-manisfest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android_version" }
android-library = { id = "com.android.library", version.ref = "android_version" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin_version" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless_version" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp_version" }
