[versions]
agp = "8.1.1"
kotlin = "1.8.10"
ksp = "1.8.10-1.0.9"
spotless = "6.14.1"
core = "1.10.1"
junit = "4.13.2"
room = "2.5.2"
lifecycle = "2.6.1"
accompanist = "0.30.1"
navigation = "2.6.0"
activity = "1.7.2"
truth = "1.1.3"
test = "1.1.5"
espresso = "3.5.1"
compose_bom = "2023.06.01"
turbine = "0.12.3"
core-splashscreen = "1.0.1"
concurrent = "1.1.0"
camera = "1.3.0-beta01"
coil = "2.4.0"
media3 = "1.1.0"
graphics = "1.0.0-alpha03"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
room_compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }
lifecycle-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
accompanist-painter = { group = "com.google.accompanist", name = "accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "test" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }
concurrent-kts = { group = "androidx.concurrent", name = "concurrent-futures-ktx", version.ref = "concurrent" }
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "camera" }
camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camera" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camera" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camera" }
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "media3" }
media3-effect = { group = "androidx.media3", name = "media3-effect", version.ref = "media3" }
media3-transformer = { group = "androidx.media3", name = "media3-transformer", version.ref = "media3" }
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
graphics-shapes = { group = "androidx.graphics", name = "graphics-shapes", version.ref = "graphics" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose_bom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-test-manisfest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
